### ISSUE TITLE
Can't find the source for the project on PyPI

### ISSUE THREAD

**Issue by jaraco** [jaraco/goto-http-redirect-server#1]
@jtmoon79, I found your project on PyPI, but the links to bugs and source are 404.

Is this project intentionally hidden from the world? I'm interested in contributing to it.

**Comment by jtmoon79** [comment]
Umm... it's in transition right now, long story. Check back in a month.  I am interested in your contribution! ☺️

**Comment by jtmoon79** [comment]
... and it's back!
CC @jaraco

**Comment by jaraco** [comment]
Awesome! Thanks... 

now if I can just remember what it was I was hoping to use this for.
